### ISSUE TITLE
Broken on ST3 Build 3126

### ISSUE THREAD

**Issue by hozza** [bistory/Sublime-Minifier#26]
Looks like the plugin in broken on the Build 3126 of Sublime Text 3... after update I keep getting generic "There was an error while minifiying file"

Discovered on Linux

**Comment by quentinHydrobat** [comment]
same here,
Logs : 

```
error: There was an error minifying the file.
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 168, in run
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 46, in run
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 73, in handle_threads
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 180, in handle_result
AttributeError: 'NoneType' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "trailing_spaces in /home/storm1er/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 416, in on_selection_modified
  File "trailing_spaces in /home/storm1er/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 129, in match_trailing_spaces
  File "trailing_spaces in /home/storm1er/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 86, in find_trailing_spaces
  File "/opt/sublime_text/sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 168, in run
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 46, in run
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 73, in handle_threads
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 180, in handle_result
AttributeError: 'NoneType' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "/home/storm1er/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1520, in on_selection_modified
    rowcol = view.rowcol(view_sel[0].end())
  File "/opt/sublime_text/sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 168, in run
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 46, in run
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 73, in handle_threads
  File "Minify in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 180, in handle_result
AttributeError: 'NoneType' object has no attribute 'decode'
Exception in thread Thread-32:
Traceback (most recent call last):
  File "compilers.basecall in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 39, in run
  File "compilers.uglifycall in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 26, in exec_request
AttributeError: 'module' object has no attribute 'parse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "compilers.basecall in /home/storm1er/.config/sublime-text-3/Installed Packages/Minifier.sublime-package", line 40, in run
AttributeError: 'module' object has no attribute 'error'

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "trailing_spaces in /home/storm1er/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 421, in on_activated
  File "trailing_spaces in /home/storm1er/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 129, in match_trailing_spaces
  File "trailing_spaces in /home/storm1er/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 86, in find_trailing_spaces
  File "/opt/sublime_text/sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
```

**Comment by bistory** [comment]
Hi guys,

PR are welcome as I don't have time to maintain this plugin anymore...

**Comment by hozza** [comment]
Python is not my forte unfortunately, maybe you could have the Package Control entry altered to say incompatible with ST3?

**Comment by bistory** [comment]
It was until this latest update. Unfortunately, I didn't see any breaking changes notices for plugins. Maybe it's a Sublime Text bug ?

**Comment by hozza** [comment]
OK cheers. I'll keep an eye on it and close the ticket if a future ST3 beta update fixes the issue. :)

**Comment by bistory** [comment]
This seems to be fixed.
